# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/PyCQA/isort
    rev: '5.13.0'
    hooks:
    -   id: isort
        entry: isort --diff --check source tests
        pass_filenames: false
        language_version: python3.12
        always_run: true

-   repo: https://github.com/ambv/black
    rev: '24.3.0'
    hooks:
    - id: black
      name: black
      entry: black --diff --check --color source tests
      pass_filenames: false
      language_version: python3.12
      always_run: true

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.9.0'
    hooks:
    -   id: mypy
        # when mypy is run from the pre-commit hook an error occurs due to missing stubs, so we need these flags
        entry: mypy --install-types --non-interactive source tests --explicit-package-bases
        pass_filenames: false
        language_version: python3.12
        always_run: true

