version: '3'

services:
  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <YOUR_MYSQL_ROOT_PASSWORD>
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  setup_db:
    image: mysql:8.3.0
    depends_on:
      - mysql
    volumes:
      - ./setup:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: <YOUR_MYSQL_ROOT_PASSWORD>
      MYSQL_DATABASE: <YOUR_DATABASE_NAME>
      MYSQL_USER: root
      MYSQL_PASSWORD: <YOUR_MYSQL_ROOT_PASSWORD>

volumes:
  mysql_data:

