# `black` does not work with setup.cfg
# as seen here: https://blog.pilosus.org/posts/2019/12/26/python-third-party-tools-configuration/



[tool.flake8]
max-line-length = 132
max-complexity = 20
exclude = [
    # List of directories or files to exclude from linting
]
extend-ignore = [
    # List of error codes to ignore
]

[tool.pytest]
addopts = "-ra -q --durations=5 -s"
testpaths = [
    "tests"
]
pythonpath = [
    "source"
]

[mypy]
ignore_missing_imports = true
namespace_packages = true
follow_imports = "skip" # used for https://github.com/python/mypy/issues/13627 since we cant update mypy

[tool.coverage.report]
show_missing = true
omit = ["*/__init__.py",
    ".mypy_cache",
    ".pytest_cache"
]

[tool.coverage.xml]
output = "coverage-reports/cobertura-coverage.xml"

[tool.coverage.run]
source = ["airflow_template"]
branch = true
relative_files = true
omit = ["*/__init__.py",
    ".mypy_cache",
    "tests/",
    "notebooks/",
    "docs/",
    ".git"
]

